# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
cache: cocoapods
podfile: Example/Podfile
branches:
  only:
  - master
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
# - brew update
# - brew outdated xctool || brew upgrade xctool
script:
- xcodebuild -workspace Example/AlamofireOAuth1.xcworkspace -scheme AlamofireOAuth1-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
# - xctool test -workspace Example/AlamofireOAuth1.xcworkspace -scheme AlamofireOAuth1-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --allow-warnings
- pod spec lint --allow-warnings
# - pod trunk push --allow-warnings
